build:
    zip:
        composer:
            enabled: true
        assets:
            enabled: true
            enable_es_build_for_admin: true
            enable_es_build_for_storefront: true
        pack:
            excludes:
                paths:
                    - .idea
                    - var
                    - .gitignore
