name: Build extension
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    uses: shopware/github-actions/.github/workflows/build-zip.yml@main
    with:
      extensionName: ${{ github.event.repository.name }}
