name: PHP
on:
  pull_request:
    paths:
      - '**/*.php'
      - .github/workflows/php.yml
  push:
    paths:
      - '**/*.php'
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  phpunit:
    strategy:
      fail-fast: false
      matrix:
        shopware-version:
          - '6.5.x'
          - '6.6.x'
    uses: shopware/github-actions/.github/workflows/phpunit.yml@main
    with:
      extensionName: ${{ github.event.repository.name }}
      shopwareVersion: ${{ matrix.shopware-version }}
      uploadCoverage: true
    secrets:
      codecovToken: ${{ secrets.CODECOV_TOKEN }}
