name: PHPUnit
on:
    push:
        branches:
            - 'main'
        tags-ignore:
            - '*'
    pull_request:

jobs:
    phpunit:
        name: Run tests
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                shopware-version:
                    - 'v6.5.2.0'
                    - 'v6.5.3.2'
                    - 'trunk'
        steps:
            - name: Setup Shopware
              uses: FriendsOfShopware/setup-shopware@main
              with:
                shopware-version: ${{ matrix.shopware-version }}
                php-version: 8.1

            - name: Checkout
              uses: actions/checkout@v3
              with:
                  path: custom/plugins/FroshPlatformTemplateMail

            - name: Run Tests
              run: |
                  cd custom/plugins/FroshPlatformTemplateMail/
                  php -d pcov.enabled=1 ../../../vendor/bin/phpunit --coverage-clover clover.xml

            - name: Upload coverage
              uses: codecov/codecov-action@v3
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
              with:
                files: ./clover.xml
                root_dir: /home/runner/work/FroshPlatformTemplateMail/FroshPlatformTemplateMail/custom/plugins/FroshPlatformTemplateMail/
                working-directory: /home/runner/work/FroshPlatformTemplateMail/FroshPlatformTemplateMail/custom/plugins/FroshPlatformTemplateMail/
