name: PHPUnit
on:
    push:
        branches:
            - '1.x'
        tags-ignore:
            - '*'
    pull_request:

env:
    PLUGIN_NAME: FroshPlatformTemplateMail

jobs:
    phpunit:
        name: Run tests
        container: ghcr.io/friendsofshopware/platform-plugin-dev:v6.4.17
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    path: ${{ env.PLUGIN_NAME }}

            -   name: Run Tests
                run: |
                    cp -r "./${PLUGIN_NAME}" "/plugins/${PLUGIN_NAME}"
                    shopware-cli extension prepare "/plugins/${PLUGIN_NAME}"
                    start-mysql
                    export PROJECT_ROOT=/opt/shopware
                    /opt/shopware/bin/console plugin:refresh
                    /opt/shopware/bin/console plugin:install --activate -c ${PLUGIN_NAME}
                    cd /opt/shopware/custom/plugins/${PLUGIN_NAME}
                    php -d pcov.enabled=1 /opt/shopware/vendor/bin/phpunit --coverage-clover clover.xml

            - uses: codecov/codecov-action@v1
              with:
                file: ./clover.xml
                root_dir: /plugins/FroshPlatformTemplateMail
                working-directory: /plugins/FroshPlatformTemplateMail

