name: PHPUnit
on:
    push:
        branches:
            - 'main'
        tags-ignore:
            - '*'
    pull_request:

jobs:
    phpunit:
        name: Run tests
        container: ghcr.io/friendsofshopware/platform-plugin-dev:v6.5.0
        runs-on: ubuntu-latest
        steps:
            - name: Setup Shopware
              uses: FriendsOfShopware/setup-shopware@main
              
            -
                name: Install Shopware CLI
                uses: FriendsOfShopware/shopware-cli-action@v1
                env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    path: custom/plugins/FroshPlatformTemplateMail
                    
            - name: Prepare Plugin
              run: shopware-cli extension prepare custom/plugins/FroshPlatformTemplateMail

            - name: Run Tests
              run: php -d pcov.enabled=1 ./vendor/bin/phpunit -c custom/plugins/FroshPlatformTemplateMail/phpunit.xml  --coverage-clover clover.xml

            - uses: codecov/codecov-action@v1
              with:
                file: ./clover.xml
