name: PHPUnit
on:
    push:
        branches:
            - 'master'
        tags:
            - '*'

env:
    PLUGIN_NAME: FroshPlatformTemplateMail

jobs:
    phpunit:
        name: Run tests
        container: ghcr.io/friendsofshopware/platform-plugin-dev:v6.4.0
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2.3.1
                with:
                    path: ${{ env.PLUGIN_NAME }}

            -   name: Run Tests
                run: |
                    cp -r "./${PLUGIN_NAME}" "/plugins/${PLUGIN_NAME}"
                    /opt/bin/plugin-uploader ext:prepare "/plugins/${PLUGIN_NAME}"
                    start-mysql
                    export PROJECT_ROOT=/opt/shopware
                    /opt/shopware/bin/console plugin:refresh
                    /opt/shopware/bin/console plugin:install --activate -c ${PLUGIN_NAME}
                    php /opt/shopware/vendor/bin/phpunit -c /opt/shopware/custom/plugins/${PLUGIN_NAME}

