name: PHPUnit
on:
    push:
        branches:
            - 'main'
        tags-ignore:
            - '*'
    pull_request:

jobs:
    phpunit:
        name: Run tests
        runs-on: ubuntu-latest
        steps:
            - name: Setup Shopware
              uses: FriendsOfShopware/setup-shopware@main

            - name: Checkout
              uses: actions/checkout@v3
              with:
                  path: custom/plugins/FroshPlatformTemplateMail

            - name: Run Tests
              run: php -d pcov.enabled=1 ./vendor/bin/phpunit -c custom/plugins/FroshPlatformTemplateMail/phpunit.xml  --coverage-clover clover.xml

            - name: Upload coverage
              uses: codecov/codecov-action@v1
              with:
                file: ./clover.xml
