name: PHPUnit
on:
    push:
        branches:
            - 'main'
        tags-ignore:
            - '*'
    pull_request:

jobs:
    phpunit:
        name: Run tests
        strategy:
            fail-fast: false
            matrix:
                shopware-version:
                    - '6.5.x'
                    - 'v6.6.0.0-rc2'
        uses: shopware/github-actions/.github/workflows/phpunit.yml@main
        with:
          extensionName: ${{ github.event.repository.name }}
          shopwareVersion: ${{ matrix.shopware-version }}
          uploadCoverage: true
        secrets:
          codecovToken: ${{ secrets.CODECOV_TOKEN }}
